language: python

python:
  - "2.7"
  - "3.5"

env:
  - PENDULUM_EXTENSIONS=1
  - PENDULUM_EXTENSIONS=0

before_install:
  - pip install codecov

install:
  - pip install -r tests-requirements.txt
  - python setup.py develop

script: py.test --cov=pendulum --cov-config=.coveragerc tests/

after_success:
  - codecov
