[tool.poetry]
name = "pendulum"
version = "2.0.5"
description = "Python datetimes made easy"
authors = ["Sébastien Eustace <sebastien@eustace.io>"]
license = "MIT"
readme = 'README.rst'
homepage = "https://pendulum.eustace.io"
repository = "https://github.com/sdispater/pendulum"
documentation = "https://pendulum.eustace.io/docs"
keywords = ['datetime', 'date', 'time']

build = "build.py"

packages = [
    {include = "pendulum"},
    {include = "tests", format = "sdist"},
]


[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
python-dateutil = "^2.6"
pytzdata = ">=2018.3"

# typing is needed for Python < 3.5
typing = { version = "^3.6", python = "<3.5" }

[tool.poetry.dev-dependencies]
pytest = "^4.6"
pytest-cov = "^2.5"
pytz = ">=2018.3"
babel = "^2.5"
cleo = "^0.7.5"
tox = "^3.0"
black = { version = "^19.3b0", markers = "python_version >= '3.6' and python_version < '4.0' and implementation_name != 'pypy'" }
pre-commit = "^1.10"


[build-system]
requires = ["poetry>=1.0.0b1"]
build-backend = "poetry.masonry.api"
